# Generated by Django 3.1.7 on 2021-03-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
